import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'firebase_auth_service.dart';
import 'info_screen.dart';

const String termsOfServiceContent = """
**Terms of Service for SolarTrack Pro**

Last Updated: 2024-05-17

Welcome to SolarTrack Pro! By using our application, you agree to these terms. Please read them carefully.

**1. Service Description**
SolarTrack Pro is a mobile application designed to monitor and control a personal solar tracking device. The service provides real-time data, analytics, and remote control functionalities.

**2. User Accounts**
To access the service, you must create an account. You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account.

**3. User Conduct**
You agree not to use the service for any unlawful purpose. You are solely responsible for the physical setup, maintenance, and safe operation of your hardware. The developers of SolarTrack Pro are not liable for any damage to hardware or property resulting from the use or misuse of this application.

**4. Data and Privacy**
We collect data on your device's performance (e.g., energy generation, sensor readings) to provide you with analytics. We do not share your personal data with third parties. Your account information is stored securely.

**5. Disclaimers**
The service is provided "as is" without any warranties. We do not guarantee that the service will be uninterrupted or error-free. The accuracy of sensor data is dependent on your hardware setup and calibration.

**6. Limitation of Liability**
In no event shall the developers of SolarTrack Pro be liable for any indirect, incidental, or consequential damages arising out of the use of this application.

**7. Changes to Terms**
We reserve the right to modify these terms at any time. We will notify you of any changes by posting the new Terms of Service within the app.
""";

const String helpAndSupportContent = """
**SolarTrack Pro - Help & Support**

Welcome to the Help Guide. Here is a brief overview of the app's main features.

**1. Home Screen**
This is your main dashboard. It provides a real-time overview of your solar tracker's status:
- **Current Power Output:** The instantaneous power being generated by your solar panel in Watts.
- **Metrics Grid:** Shows key data points like servo angles, wind speed, battery level and voltage, today's total generated energy, and the current dust level.
- **Quick Actions:** Buttons to quickly navigate to the Live Camera/Dust Analysis view and the Manual Control screen.

**2. Device Tab**
This screen shows information about your paired hardware device. You can see its unique ID, model, and firmware version. You can also tap the 'edit' icon to give your device a custom name.

**3. Analytics Tab**
This screen visualizes the historical energy production of your device. You can select a custom date range and toggle the display unit between Watt-hours (Wh) and kilowatt-hours (kWh). The summary cards provide an overview of the total, peak, and average generation for the selected period.

**4. Settings Tab**
This screen allows you to configure your device's automated behaviors and your alert preferences:
- **Storm Protection:** You can enable or disable the entire storm protection feature. When enabled, you can set the wind speed threshold that will cause the device to move to its safe angle.
- **Alerts:** You can separately enable or disable alerts for high winds and dust levels, and set the specific thresholds for when these alerts should be triggered.

**5. Manual Control Screen**
This screen gives you direct control over the tracker. You must first switch the mode to "Manual". You can then use the directional buttons to move the panel in 10-degree increments or tap on the angle display to enter a precise degree.

**Contact Support**
If you have any further questions or encounter any issues, please do not hesitate to contact our support team at: **support@solartrackpro.com**
""";

class ProfileScreen extends StatefulWidget {
  const ProfileScreen({super.key});

  @override
  State<ProfileScreen> createState() => _ProfileScreenState();
}

class _ProfileScreenState extends State<ProfileScreen> {
  final AuthService _authService = AuthService();
  final User? _currentUser = FirebaseAuth.instance.currentUser;

  Future<void> _handleChangePassword() async {
    if (_currentUser?.email == null) return;
    try {
      await _authService.sendPasswordResetEmail(_currentUser!.email!);
      if (mounted) {
        _showInfoDialog('Check Your Email', 'A password reset link has been sent to your email address.');
      }
    } catch (e) {
      if (mounted) {
        _showInfoDialog('Error', 'Failed to send password reset email. Please try again later.');
      }
    }
  }

  void _showInfoDialog(String title, String content) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(title),
        content: Text(content),
        actions: [TextButton(onPressed: () => Navigator.of(context).pop(), child: const Text('OK'))],
      ),
    );
  }

  void _navigateToInfoScreen(String title, String content) {
    Navigator.of(context).push(
      MaterialPageRoute(
        builder: (context) => InfoScreen(title: title, content: content),
      ),
    );
  }

  void _handleLogout() {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Logout'),
          content: const Text('Are you sure you want to sign out?'),
          actions: <Widget>[
            TextButton(child: const Text('Cancel'), onPressed: () => Navigator.of(context).pop()),
            TextButton(
              onPressed: () async {
                await _authService.signOut();
                if (mounted) {
                  Navigator.of(context).pushNamedAndRemoveUntil('/login', (route) => false);
                }
              },
              child: const Text('Logout', style: TextStyle(color: Colors.red)),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final user = _currentUser;
    if (user == null) return const Scaffold();

    final String displayName = user.displayName ?? user.email?.split('@')[0] ?? 'User';
    final String email = user.email ?? 'No email';
    final String photoUrl = user.photoURL ?? '';

    return Scaffold(
      appBar: AppBar(
        title: const Text('Profile', style: TextStyle(fontWeight: FontWeight.bold)),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Card(
              child: Padding(
                padding: const EdgeInsets.symmetric(vertical: 20.0),
                child: Column(
                  children: [
                    CircleAvatar(
                      radius: 40,
                      backgroundImage: photoUrl.isNotEmpty ? NetworkImage(photoUrl) : null,
                      child: photoUrl.isEmpty ? Text(displayName.length >= 2 ? displayName.substring(0, 2).toUpperCase() : displayName.toUpperCase(), style: const TextStyle(fontSize: 30)) : null,
                    ),
                    const SizedBox(height: 10),
                    Text(displayName, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                    Text(email, style: const TextStyle(color: Colors.grey)),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 20),
            MenuTile(title: 'Change Password', icon: Icons.lock_outline, onTap: _handleChangePassword),
            MenuTile(title: 'Help & Support', icon: Icons.help_outline, onTap: () => _navigateToInfoScreen('Help & Support', helpAndSupportContent)),
            MenuTile(title: 'Terms of Service', icon: Icons.description_outlined, onTap: () => _navigateToInfoScreen('Terms of Service', termsOfServiceContent)),
            const SizedBox(height: 40),
            ElevatedButton.icon(
              onPressed: _handleLogout,
              icon: const Icon(Icons.logout, color: Colors.white),
              label: const Text('Logout', style: TextStyle(fontSize: 18, color: Colors.white)),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.red,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class MenuTile extends StatelessWidget {
  final String title;
  final IconData icon;
  final VoidCallback onTap;

  const MenuTile({super.key, required this.title, required this.icon, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      child: ListTile(
        leading: Icon(icon, color: Colors.black54),
        title: Text(title),
        trailing: const Icon(Icons.arrow_forward_ios, size: 16, color: Colors.grey),
        onTap: onTap,
      ),
    );
  }
}
